jobs:
    compile:
        name: Compile
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - uses: ./.github/actions/prepare
            - run: npm run compile
            - run: node bin/tslint-to-eslint-config --version
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - uses: ./.github/actions/prepare
            - run: npm run prettier -- --list-different
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - uses: ./.github/actions/prepare
            - run: npm run eslint
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
            - uses: ./.github/actions/prepare
            - run: npm run test:ci

name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
