description: Prepares the repo for a typical CI job

name: Prepare

runs:
    steps:
        - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
          with:
              cache: npm
              node-version: 24.11.1
        - run: npm ci
          shell: bash
    using: composite
