description: Prepares the repo for a typical CI job

name: Prepare

runs:
    steps:
        - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
          with:
              cache: npm
              node-version: 24.11.1
        - run: npm ci
          shell: bash
    using: composite
