description: Prepares the repo for a typical CI job

name: Prepare

runs:
    steps:
        - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
          with:
              cache: npm
              node-version: 24.15.0
        - run: npm ci
          shell: bash
    using: composite
