jobs:
    compile:
        name: Compile
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/prepare
            - run: npm run compile
            - run: node bin/tslint-to-eslint-config --version
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/prepare
            - run: npm run prettier -- --list-different
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/prepare
            - run: npm run eslint
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: ./.github/actions/prepare
            - run: npm run test:ci

name: CI

on:
    pull_request: ~
    push:
        branches:
            - main
